export const tasksData: Task[] = [
  {
    id: 1,
    title: 'School Mgt Web App',
    description: 'Dashboard Design',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
  {
    id: 2,
    title: 'e Commerce Mobile App',
    description: 'Onboarding / Authentication Screen',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
  {
    id: 3,
    title: 'School Mgt Web App',
    description: 'Dashboard Design',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
  {
    id: 4,
    title: 'School Mgt Web App',
    description: 'Dashboard Design',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
  {
    id: 5,
    title: 'School Mgt Web App',
    description: 'Dashboard Design',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
  {
    id: 6,
    title: 'School Mgt Web App',
    description: 'Dashboard Design',
    date: new Date(),
    progress: '0%',
    members: ['user', 'Student'],
  },
];
